### ISSUE TITLE
Easy tweaks

### ISSUE THREAD

**Issue by tom-gu** [rahulchauhan049/dashboard.experiment#36]
##  snake_case >> Title Case
 - [ ] Data missing tab: table title should be title case instead of snake case
![image](https://user-images.githubusercontent.com/16609623/137727600-0582f663-67c6-4199-bad0-843c16f694d5.png)
 - [ ] As well as in the two field selectors (table & plot)
![image](https://user-images.githubusercontent.com/16609623/137728517-68d986c2-f0e7-4314-96c8-1ee1f4ce2fb6.png)
![image](https://user-images.githubusercontent.com/16609623/137728599-daffdc72-7cf6-44c7-8e69-641c0ca1e3ab.png)

## Field selectors
- [ ] The default active axis should have the active color:
This: 
![image](https://user-images.githubusercontent.com/16609623/137729354-1aefae97-7f72-4619-9687-d13fc46d64e0.png)
Should be this:
![image](https://user-images.githubusercontent.com/16609623/137729448-8e80f8ea-ba0e-4371-b3e1-73de0d2f3dca.png)
- [ ] Table field selector: unifying button look 
![image](https://user-images.githubusercontent.com/16609623/137732481-5a97f51b-c9c0-4dcb-9e96-a40f02ec3f13.png)
To:
![image](https://user-images.githubusercontent.com/16609623/137733689-f0f51370-c621-416f-905a-892d982fe137.png)

## Removing button text (icon only is intuitive enough)
 
![image](https://user-images.githubusercontent.com/16609623/137732995-18a69e90-518a-43f9-9d6e-6654a0f8ba6d.png)
![image](https://user-images.githubusercontent.com/16609623/137733039-a9e8a602-e961-46aa-958e-437f94bec5a0.png)
![image](https://user-images.githubusercontent.com/16609623/137733124-7d9e09f9-b73a-4d1f-882a-95f19098678b.png)

## Map
- [ ]  Open TopoMap should be the default map

**Comment by rahulchauhan049** [comment]
I am on it.
